name: doc

on:
  push:
    tags:
      - '**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # needed for setuptools_scm
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - run: sudo apt-get install pandoc
    - run: python -m pip install --prefer-binary -v -e .[doc]
    - run: python -m ipykernel install --user --name python3
    - run: python doc/build.py

    - uses: actions/upload-pages-artifact@v1
      with:
        path: doc/_build/html

  deploy:
    if: contains(github.event.ref, '/tags/')
    needs: build
    # Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/configure-pages@v2
    - uses: actions/deploy-pages@v1
