name: Docs

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Many color libraries just need this to be set to any value, but at least
  # one distinguishes color depth, where "3" -> "256-bit color".
  FORCE_COLOR: 3

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: read # to check out the repository
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v10.1.0

      - name: Build the documentation
        run: uvx nox -s docs

      - uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_build/html

  deploy:
    name: Deploy docs to GitHub Pages
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'release' && github.event.action == 'published')
    needs: [build]
    permissions:
      contents: read # to read the repository settings
      pages: write # to deploy to GitHub Pages
      id-token: write # to verify the deployment originates from this workflow
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6

      - id: deployment
        uses: actions/deploy-pages@v5
