on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - run: python -m pip install -e .[doc]
    - run: python doc/build.py
    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref_type == 'tag' || github.ref_name == 'main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html
