name: test

on:
  pull_request:
    paths-ignore:
      - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # version number must be string, otherwise 3.10 becomes 3.1
          - os: windows-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "pypy-3.8"
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install --upgrade pip
    - run: python -m pip install --prefer-binary -v -e '.[test]'
    - run: python -m pytest
